export const language = {
    alreadyHaveAccount: "Already have an account",
    changeCountryCode: "Change country code",
    close: "Close",
    continue: "Continue",
    email: "Email Address",
    emailPassword: "Email & Password",
    error: "Error",
    firstName: "First Name",
    invalidCode: "Codes do not match",
    invalidCredentials: "Unable to log in with provided credentials",
    invalidEmail: "Please enter a valid email address",
    invalidName: "Please enter a valid name",
    invalidPassword: "Please enter a valid password",
    invalidPhone: "Please enter a valid phone number",
    lastName: "Last Name",
    logIn: "Log in",
    finish: "Finish",
    forgotPassword: "Forgot your password?",
    fullName: "Full Name",
    password: "Password",
    passwordRequirements: "10 characters, 1 number, 1 symbol",
    phoneNumber: "Phone Number",
    phoneNumberConfirm: "Confirm your phone number",
    phoneNumberVerify: "Verify your phone number",
    phoneNumberVerifyPlaceholder: "XXXXXX",
    phoneNumberVerifySent: "A text message with a verification code has been sent to",
    phoneNumberVerified: "Your phone number is verified, your account is now active",
    privacyPolicy: "You are consenting to be contacted at this phone number for the purpose of receiving a verification code from Centigro",
    resend: "Resend",
    resetPassword: "Reset your password",
    resetPasswordInstructions: "Please enter the email address associated with your account. We'll send you an email with instructions on how to reset your password.",
    sendEmail: "Send email",
    signUp: "Sign up",
    signUpSuccess: "Success!",
    sixDigitCode: "We'll send you a six digit code, it expires 10 minutes you request it",
    textMe: "Text me",
    welcomeBack: "Welcome back!",
    welcomeBody: "Do good for your community",
    welcomeHeader: "Welcome to Centigro",
}