kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  type: ClusterIP
  # type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      # protocol: TCP
      # nodePort: 32500
