kind: Deployment
apiVersion: apps/v1
metadata:
  name: ctweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ctweb
  template:
    metadata:
      labels:
        app: ctweb
    spec:
      containers:
        - name: ctweb
          image: manalaro1/ctweb
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: ctapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ctapi
  template:
    metadata:
      labels:
        app: ctapi
    spec:
      containers:
        - name: ctapi
          image: manalaro1/ctapi
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always