kind: Deployment
apiVersion: apps/v1
metadata:
  name: ctweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ctweb
  template:
    metadata:
      labels:
        app: ctweb
    spec:
      containers:
        - name: ctweb
          image: nickj202/ctweb_centigro-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: iam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
        - name: iam
          image: nickj202/iam
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always