version: '3.9'

services:
  db:
    platform: linux/amd64
    image: amd64/postgres
    ports:
      - "5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    platform: linux/amd64
    container_name: api
    build: ./iam
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/iam/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    depends_on:
      - db
  
  web:
    platform: linux/amd64
    container_name: web
    build: ./ctweb
    ports:
      - '8080:80'

volumes:
  postgres_data: