kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000

---

kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 31100

---

kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  type: NodePort
  ports:
    selector:
      app: api
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 32000