kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      externalIPS: 0.0.0.0
      # protocol: TCP
      # nodePort: 31000

---

kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      # protocol: TCP
      # nodePort: 31100

---

kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  type: ClusterIP
  selector:
      app: api
  ports:
    - port: 8000
      targetPort: 8000
      # protocol: TCP
      # nodePort: 32000