kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: web

---

kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 5432
  selector:
    app: api

---

kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 32000
  selector:
    app: api