kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  # type: LoadBalancer
  # loadBalancerIP: 192.168.1.1
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000