kind: Deployment
apiVersion: apps/v1
metadata:
  name: ctweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ctweb
  template:
    metadata:
      labels:
        app: ctweb
    spec:
      containers:
        - name: ctweb
          image: nickj202/ctweb_centigro-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: ctweb
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: ctweb
